# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Custom vars
version:             1.0.0
updatedate:          2016-05-25

# Build settings
markdown:            kramdown
sass:
    style:           compressed
    sass_dir:        _sass

# from Github's settings
github:             [metadata]
kramdown:
  input:            GFM
  hard_wrap:        false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist

# About/contact
author:
  name:              Yifeng Huang
  url:               https://winddweb.github.io/blog
  email:             winddweb@gmail.com

twitter_username:    winddweb
github_username:     winddweb

repository:          winddweb/blog

# Site settings
title:               Winddweb's Log
tagline: >
  I don't know programming. I don't know photography. I don't know drawing.

description: > # this means to ignore newlines until "baseurl:"
  I don't know programming. I don't know photography. I don't know drawing. Winddweb, I am not sure what it means. Maybe it means wind the web around me.

# baseurl:             /blog # the subpath of your site, e.g. /blog
baseurl:
url:                 https://winddweb.github.io # the base hostname & protocol for your site
timezone:            America/Los_Angeles
paginate:            5
google_analytics:    UA-93452603-1

# Permalinks#
permalink:           /:slug

# Include _pages folder for single pages
include:            ["_pages"]

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:            [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]